DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS TRANSACTION;

DROP SEQUENCE IF EXISTS ACCOUNT_SEQ;
DROP SEQUENCE IF EXISTS TRANSACTION_SEQ;

CREATE SEQUENCE ACCOUNT_SEQ INCREMENT BY 1 MINVALUE 1000;
CREATE SEQUENCE TRANSACTION_SEQ INCREMENT BY 1 MINVALUE 1000;

CREATE TABLE ACCOUNT(ID BIGINT DEFAULT ACCOUNT_SEQ.NEXTVAL PRIMARY KEY, OWNER VARCHAR(100), BALANCE DECIMAL(10,2), CREATE_DATE DATETIME);
CREATE TABLE TRANSACTION(ID BIGINT DEFAULT TRANSACTION_SEQ.NEXTVAL PRIMARY KEY, FROM_ACCOUNT BIGINT, TO_ACCOUNT BIGINT, AMOUNT DECIMAL(10,2), CREATE_DATE DATETIME);
